apiVersion: batch/v1
kind: CronJob
metadata:
  name: msynbot.wdadminstats
  labels:
    name: msynbot.wdadminstats
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "42 6 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: wdadminstats
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            command: [ "/data/project/msynbot/pywikibot_tasks/wd_adminstats/venv/bin/python3" ]
            args: [ "/data/project/shared/pywikibot/stable/pwb.py", "/data/project/msynbot/pywikibot_tasks/wd_adminstats/main.py" ]
            workingDir: /data/project/msynbot/pywikibot_tasks/wd_adminstats
            env:
            - name: HOME
              value: /data/project/msynbot
          restartPolicy: OnFailure
